(() => {
"use strict";
const routes=[...document.querySelectorAll(".route")],links=[...document.querySelectorAll("[data-route]")],nav=document.querySelector("#siteNav"),menu=document.querySelector("#menuButton");
const diagnoses={
sour:{title:"Start by checking extraction",body:"Sharp or sour flavours can be associated with insufficient extraction, but taste alone is not a complete diagnosis.",actions:["Keep your dose and target yield the same for the next test.","Try a slightly finer grind and compare the cup.","If the shot is also extremely fast, grind size is an especially useful place to start.","If it remains sour after sensible adjustments, consider whether the coffee's roast or inherent flavour is contributing."]},
bitter:{title:"Check extraction and evenness",body:"Bitterness or dryness can occur with excessive extraction, but uneven extraction can produce bitterness and sourness in the same drink.",actions:["Do not automatically make the grind coarser if the shot is spraying or channeling.","Check distribution and puck preparation first.","If the flow is otherwise controlled, try a slightly coarser grind and compare the result.","Taste the new shot before making another change."]},
fast:{title:"Look at resistance and flow",body:"A very fast shot often means the coffee bed is offering too little resistance. Grind size is the simplest variable to test first.",actions:["Keep dose and target yield unchanged.","Move slightly finer and pull another shot.","Check that the basket is appropriate for the dose and that the puck is evenly distributed.","If a finer setting causes severe channeling, the grinder or puck preparation may be limiting you."]},
slow:{title:"Look for excessive resistance",body:"Very slow flow can come from a grind that is too fine, an overloaded basket, or other preparation and machine factors.",actions:["Confirm that your dose suits the basket.","Try a slightly coarser grind.","Check that the puck is not being disturbed or prepared unevenly.","If flow remains abnormal, check the machine and basket rather than repeatedly changing the grind."]},
spray:{title:"Treat spraying as a flow problem",body:"Visible spraying from a bottomless portafilter can indicate channeling: water is finding a lower-resistance path through the puck.",actions:["Improve distribution before tamping.","Break up obvious clumps if your workflow produces them.","Tamp level and consistently.","Do not assume every visual imperfection is a taste defect; taste the shot as well."]},
good:{title:"Keep the coffee you like",body:"A conventional shot time is a reference point, not a quality score. If the coffee tastes good and the workflow is repeatable, there may be no problem to fix.",actions:["Record the recipe so you can reproduce it.","If you want to experiment, change one variable at a time.","Do not sacrifice a good cup just to make the timer look familiar."]}
};
function showRoute(name,updateHash=true){const target=document.getElementById(name)?name:"start";routes.forEach(r=>r.classList.toggle("active",r.id===target));links.forEach(l=>l.classList.toggle("active",l.dataset.route===target));if(updateHash)history.replaceState(null,"","#"+target);window.scrollTo({top:0,behavior:"auto"});nav?.classList.remove("open");menu?.setAttribute("aria-expanded","false")}
function handleRoute(){showRoute(location.hash.replace("#","")||"start",false)}
links.forEach(l=>l.addEventListener("click",e=>{const route=l.dataset.route;if(!route)return;e.preventDefault();showRoute(route)});
window.addEventListener("hashchange",handleRoute);
menu?.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open))});
const buttons=[...document.querySelectorAll(".diagnostic")],panel=document.querySelector("#diagnosisPanel");
function renderDiagnosis(key){const d=diagnoses[key];if(!d||!panel)return;panel.innerHTML="<h2>"+d.title+"</h2><p>"+d.body+"</p><ul>"+d.actions.map(item=>"<li>"+item+"</li>").join("")+"</ul>";buttons.forEach(b=>b.classList.toggle("active",b.dataset.diagnosis===key))}
buttons.forEach(b=>b.addEventListener("click",()=>renderDiagnosis(b.dataset.diagnosis)));renderDiagnosis("sour");handleRoute();
})();